apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: express-ns
spec:
  replicas: 3 # Increased for high availability
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: django
        image: dev126712/express-api:dr8f9g9gg9f8f7dnmds2
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
        envFrom:
          - configMapRef:
              name: backend-config
        env:
          - name: DB_URI
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: DB_URI
          - name: ARCJET_KEY
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: ARCJET_KEY
          - name: QSTASH_TOKEN
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: QSTASH_TOKEN # Mount logs to this path inside the container
        ports:
        - containerPort: 5500
        resources: # Prevents pod from crashing the node
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe: # Restarts pod if it hangs
          httpGet:
            path: /
            port: 5500
          initialDelaySeconds: 15
          timeoutSeconds: 5       # CRITICAL: Increases wait time from 1s to 5s
          failureThreshold: 3
          periodSeconds: 20
        readinessProbe: # Don't send traffic until DB is connected
          httpGet:
            path: /
            port: 5500
          initialDelaySeconds: 20  # Increased to give Mongo time
          timeoutSeconds: 10       # Increased to 10s to avoid the 'deadline exceeded'
          periodSeconds: 10
#        volumeMounts:
#          - name: backend-logs
#            mountPath: /app/logs
#
#      volume:
#        - name: backend-logs
#          emptyDir: {} # Temporary storage for logs, cleared on pod restart
