apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: express-ns
type: Opaque
data:
  DB_URI: "bW9uZ29kYitzcnY6Ly9zdGZvcnRhMV9kYl91c2VyOjhSSkYycVVVSm9BVmt0aHFAY2x1c3RlcjAuenF2d25obS5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA=="
  ARCJET_KEY: "YWprZXlfMDFrNmp5ZDd3NmY2MXI3eTV5Y2c0cjA5ams="
  QSTASH_TOKEN: "ZXlKVmMyVnlTVVFpT2lKa1pXWmhkV3gwVlhObGNpSXNJbEJoYzNOM2IzSmtJam9pWkdWbVlYVnNkRkJoYzNOM2IzSmtJbjA="