apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-bootstrap
  namespace: argocd
spec:
  project: default
  source:
    repoURL:
    path: 
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
